apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: gcr.io/PROJECT_ID/odoo-app:latest
        ports:
        - containerPort: 8069
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: db_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: db_password
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /web/health
            port: 8069
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /web/health
            port: 8069
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8069
  selector:
    app: odoo
